[package]
name = "edit_value"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.33.1"
winapi = { version = "0.3", features = ["memoryapi", "processthreadsapi", "handleapi", "winnt"] }
